import { Console, Effect, Schema } from "effect";

class CommandDescription extends Schema.Class<CommandDescription>("CommandDescription")({
  arguments: Schema.optional(Schema.Array(Schema.String)),
  artifacts: Schema.Boolean,
  command: Schema.String,
  dryRun: Schema.Boolean,
  env: Schema.Array(Schema.String),
  fieldMask: Schema.Boolean,
  flags: Schema.Array(Schema.String),
  inputs: Schema.optional(Schema.Array(Schema.String)),
  mutates: Schema.Boolean,
  outputs: Schema.Array(Schema.String),
  purpose: Schema.String,
  resultSchema: Schema.String,
}) {}

const commandDescriptions = [
  CommandDescription.make({
    artifacts: true,
    command: "check",
    dryRun: false,
    env: ["TAIZN_TARGET", "TAIZN_TIZEN_CLI", "TAIZN_SDB"],
    fieldMask: true,
    flags: ["--json", "--artifact <path>", "--fields <mask>"],
    mutates: false,
    outputs: ["text", "json", "artifact"],
    purpose: "Verify Tizen CLI, sdb, configured target, and connected target inventory.",
    resultSchema: "CheckResult",
  }),
  CommandDescription.make({
    arguments: ["query?"],
    artifacts: true,
    command: "apps",
    dryRun: false,
    env: ["TAIZN_TARGET", "TAIZN_SDB"],
    fieldMask: true,
    flags: ["--json", "--artifact <path>", "--fields <mask>"],
    mutates: false,
    outputs: ["text", "json", "artifact"],
    purpose: "List installed Tizen applications on the selected target.",
    resultSchema: "ApplicationsResult",
  }),
  CommandDescription.make({
    arguments: ["query"],
    artifacts: false,
    command: "launch",
    dryRun: true,
    env: ["TAIZN_TARGET", "TAIZN_TIZEN_CLI", "TAIZN_SDB"],
    fieldMask: false,
    flags: ["--dry-run"],
    mutates: true,
    outputs: ["text", "json"],
    purpose: "Resolve and launch an already-installed Tizen application.",
    resultSchema: "LaunchResult",
  }),
  CommandDescription.make({
    arguments: ["query"],
    artifacts: true,
    command: "prove",
    dryRun: true,
    env: ["TAIZN_TARGET", "TAIZN_TIZEN_CLI", "TAIZN_SDB"],
    fieldMask: true,
    flags: ["--json", "--artifact <path>", "--fields <mask>", "--dry-run"],
    mutates: true,
    outputs: ["text", "json", "artifact"],
    purpose: "Resolve, launch, and record proof for an installed Tizen application.",
    resultSchema: "ProofResult",
  }),
  CommandDescription.make({
    artifacts: false,
    command: "profile",
    dryRun: true,
    env: ["TAIZN_CERT_PASSWORD", "TAIZN_DIST_PASSWORD", "TAIZN_TIZEN_CLI"],
    fieldMask: false,
    flags: ["--dry-run"],
    mutates: true,
    outputs: ["text", "json"],
    purpose: "Create the configured Tizen signing profile.",
    resultSchema: "ProfileResult",
  }),
  CommandDescription.make({
    artifacts: false,
    command: "package",
    dryRun: true,
    env: ["TAIZN_VARIANT", "TAIZN_TIZEN_CLI"],
    fieldMask: false,
    flags: ["--dry-run"],
    mutates: true,
    outputs: ["text", "json"],
    purpose: "Build, stage, rewrite, and package the selected Tizen widget variant.",
    resultSchema: "PackageResult",
  }),
  CommandDescription.make({
    artifacts: false,
    command: "install",
    dryRun: true,
    env: ["TAIZN_TARGET", "TAIZN_VARIANT", "TAIZN_TIZEN_CLI", "TAIZN_SDB"],
    fieldMask: false,
    flags: ["--dry-run"],
    mutates: true,
    outputs: ["text", "json"],
    purpose: "Package and install the selected widget variant on a target.",
    resultSchema: "InstallResult",
  }),
  CommandDescription.make({
    artifacts: false,
    command: "run",
    dryRun: true,
    env: ["TAIZN_TARGET", "TAIZN_VARIANT", "TAIZN_TIZEN_CLI", "TAIZN_SDB"],
    fieldMask: false,
    flags: ["--dry-run"],
    mutates: true,
    outputs: ["text", "json"],
    purpose: "Launch the configured widget variant on a target.",
    resultSchema: "RunResult",
  }),
  CommandDescription.make({
    arguments: ["url..."],
    artifacts: true,
    command: "probe hosted-assets",
    dryRun: true,
    env: ["TAIZN_VARIANT"],
    fieldMask: true,
    flags: ["--json", "--artifact <path>", "--fields <mask>", "--dry-run"],
    inputs: ["urls"],
    mutates: false,
    outputs: ["text", "json", "artifact"],
    purpose: "Probe configured or supplied hosted asset URLs without app-specific assertions.",
    resultSchema: "HostedAssetProbeResult",
  }),
  CommandDescription.make({
    arguments: ["path"],
    artifacts: true,
    command: "inspect wgt",
    dryRun: false,
    env: [],
    fieldMask: true,
    flags: ["--json", "--artifact <path>", "--fields <mask>"],
    inputs: ["wgt"],
    mutates: false,
    outputs: ["text", "json", "artifact"],
    purpose: "Inspect a Tizen widget archive and extract neutral metadata.",
    resultSchema: "WidgetInspectionResult",
  }),
  CommandDescription.make({
    arguments: ["path"],
    artifacts: true,
    command: "prepare submission",
    dryRun: false,
    env: [],
    fieldMask: true,
    flags: ["--json", "--artifact <path>", "--fields <mask>"],
    inputs: ["wgt"],
    mutates: false,
    outputs: ["text", "json", "artifact"],
    purpose: "Create a deterministic manifest from an existing signed Tizen widget archive.",
    resultSchema: "SubmissionManifest",
  }),
  CommandDescription.make({
    arguments: ["path?"],
    artifacts: true,
    command: "validate submission",
    dryRun: false,
    env: ["TAIZN_VARIANT"],
    fieldMask: true,
    flags: ["--json", "--artifact <path>", "--fields <mask>"],
    inputs: ["wgt?"],
    mutates: false,
    outputs: ["text", "json", "artifact"],
    purpose: "Validate generic package and metadata readiness before manual TV Seller Office work.",
    resultSchema: "SubmissionValidationResult",
  }),
  CommandDescription.make({
    artifacts: true,
    command: "logs capture",
    dryRun: false,
    env: ["TAIZN_TARGET", "TAIZN_SDB"],
    fieldMask: true,
    flags: [
      "--json",
      "--output text|json|ndjson",
      "--artifact <path>",
      "--fields <mask>",
      "--app <query>",
      "--duration-ms <ms>",
    ],
    mutates: false,
    outputs: ["text", "json", "ndjson", "artifact"],
    purpose: "Capture a bounded sdb log snapshot for a target.",
    resultSchema: "LogCaptureResult",
  }),
  CommandDescription.make({
    artifacts: true,
    command: "targets list",
    dryRun: false,
    env: ["TAIZN_TARGET", "TAIZN_TV_HOST", "TAIZN_SDB"],
    fieldMask: true,
    flags: ["--json", "--artifact <path>", "--fields <mask>"],
    mutates: false,
    outputs: ["text", "json", "artifact"],
    purpose: "Show configured, aliased, and connected target state.",
    resultSchema: "TargetsResult",
  }),
  CommandDescription.make({
    artifacts: true,
    command: "targets current",
    dryRun: false,
    env: ["TAIZN_TARGET", "TAIZN_TV_HOST"],
    fieldMask: true,
    flags: ["--json", "--artifact <path>", "--fields <mask>"],
    mutates: false,
    outputs: ["text", "json", "artifact"],
    purpose: "Show the currently selected Tizen target and Samsung TV host.",
    resultSchema: "CurrentTargetResult",
  }),
  CommandDescription.make({
    artifacts: false,
    command: "seller login",
    dryRun: true,
    env: ["TAIZN_SELLER_BROWSER"],
    fieldMask: false,
    flags: ["--json", "--dry-run"],
    mutates: true,
    outputs: ["text", "json"],
    purpose:
      "Open a dedicated local Chrome profile for human-owned TV Seller Office authentication.",
    resultSchema: "SellerLoginResult",
  }),
  CommandDescription.make({
    artifacts: true,
    command: "seller apps list",
    dryRun: false,
    env: [],
    fieldMask: true,
    flags: ["--json", "--artifact <path>", "--fields <mask>"],
    mutates: false,
    outputs: ["text", "json", "artifact"],
    purpose:
      "List sanitized application identity and status from a human-authenticated TV Seller Office browser.",
    resultSchema: "SellerApplicationsResult",
  }),
  CommandDescription.make({
    artifacts: true,
    command: "tv doctor",
    dryRun: false,
    env: ["TAIZN_TARGET", "TAIZN_TV_HOST", "TAIZN_TV_TOKEN", "TAIZN_TV_TIMEOUT_MS"],
    fieldMask: true,
    flags: ["--json", "--artifact <path>", "--fields <mask>", "--connect"],
    mutates: false,
    outputs: ["text", "json", "artifact"],
    purpose:
      "Diagnose Samsung TV HTTP info, remote token state, and optional websocket reachability.",
    resultSchema: "TvDoctorResult",
  }),
  CommandDescription.make({
    artifacts: true,
    command: "tv info",
    dryRun: false,
    env: ["TAIZN_TARGET", "TAIZN_TV_HOST", "TAIZN_TV_INFO_PORT"],
    fieldMask: true,
    flags: ["--json", "--artifact <path>", "--fields <mask>"],
    mutates: false,
    outputs: ["text", "json", "artifact"],
    purpose: "Fetch neutral Samsung TV HTTP info.",
    resultSchema: "TvInfoResult",
  }),
  CommandDescription.make({
    artifacts: false,
    command: "tv pair",
    dryRun: true,
    env: ["TAIZN_TARGET", "TAIZN_TV_HOST", "TAIZN_TV_TIMEOUT_MS"],
    fieldMask: false,
    flags: ["--dry-run"],
    mutates: true,
    outputs: ["text"],
    purpose: "Pair and persist a Samsung TV websocket remote token.",
    resultSchema: "TvPairResult",
  }),
  CommandDescription.make({
    artifacts: true,
    command: "tv press",
    dryRun: true,
    env: ["TAIZN_TARGET", "TAIZN_TV_HOST", "TAIZN_TV_TOKEN", "TAIZN_TV_TIMEOUT_MS"],
    fieldMask: true,
    flags: ["--json", "--artifact <path>", "--fields <mask>", "--dry-run", "--delay-ms <ms>"],
    mutates: true,
    outputs: ["text", "json", "artifact"],
    purpose: "Send Samsung TV remote keys.",
    resultSchema: "TvPressResult",
  }),
  CommandDescription.make({
    artifacts: true,
    command: "tv script",
    dryRun: true,
    env: ["TAIZN_TARGET", "TAIZN_TV_HOST", "TAIZN_TV_TOKEN", "TAIZN_TV_TIMEOUT_MS"],
    fieldMask: false,
    flags: ["--json", "--artifact <path>", "--dry-run", "--file <path>"],
    inputs: ["json"],
    mutates: true,
    outputs: ["text", "json", "artifact"],
    purpose: "Run a JSON Samsung TV remote key script.",
    resultSchema: "TvScriptResult",
  }),
];

export const describeCli = Effect.fn("describeCli")(function* () {
  yield* Console.log(
    JSON.stringify({
      commands: commandDescriptions,
      name: "taizn",
      schemaVersion: 2,
    }),
  );
});
